services:

  api:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: crm_api
    volumes:
      - ./api:/var/www
    depends_on:
      - database
      - searcher

  controller:
    image: nginx:latest
    container_name: crm_controller
    ports:
      - "8000:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./api:/var/www
      - ./client/dist:/usr/share/nginx/html
    depends_on:
      - api

  database:
    image: mysql:8
    container_name: crm_database
    restart: always
    environment:
      MYSQL_DATABASE: crm
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  searcher:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: crm_searcher
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 15s
      timeout: 10s
      retries: 5

volumes:
  esdata: